
[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.7.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
